# -*- coding: utf-8 -*-
from accumulate_th import add_translations

d = {
  "<a data-i18n=\"nav-home\" href=\"./\">Home</a>": "<a data-i18n=\"nav-home\" href=\"./\">หน้าแรก</a>",
  "<a data-i18n=\"nav-about\" href=\"about.html\">Company Profile</a>": "<a data-i18n=\"nav-about\" href=\"about.html\">โปรไฟล์บริษัท</a>",
  "<a data-i18n=\"nav-audit\" href=\"audit.html\">Free Revenue Audit</a>": "<a data-i18n=\"nav-audit\" href=\"audit.html\">ตรวจสอบรายได้ฟรี</a>",
  "<a data-i18n=\"nav-blog\" href=\"blog.html\">Blog</a>": "<a data-i18n=\"nav-blog\" href=\"blog.html\">บล็อก</a>",
  "<a data-i18n=\"nav-contact\" href=\"contact.html\">Contact Us</a>": "<a data-i18n=\"nav-contact\" href=\"contact.html\">ติดต่อเรา</a>",
  "<a href=\"https://crscentral.com/#faq\">FAQs</a>": "<a href=\"https://crscentral.com/#faq\">คำถามที่พบบ่อย</a>",
  "<a href=\"thailand.html\">Thailand</a>": "<a href=\"thailand.html\">ประเทศไทย</a>",
  "<a href=\"laos.html\">Laos</a>": "<a href=\"laos.html\">ลาว</a>",
  "<a href=\"malaysia.html\">Malaysia</a>": "<a href=\"malaysia.html\">มาเลเซีย</a>",
  "<a href=\"vietnam.html\">Vietnam</a>": "<a href=\"vietnam.html\">เวียดนาม</a>",
  "<a href=\"india.html\">India</a>": "<a href=\"india.html\">อินเดีย</a>",
  "<a href=\"nepal.html\">Nepal</a>": "<a href=\"nepal.html\">เนปาล</a>",
  "<a href=\"services.html#service-1\" style=\"font-size: 0.85rem;\">Revenue Management</a>": "<a href=\"services.html#service-1\" style=\"font-size: 0.85rem;\">การจัดการรายได้</a>",
  "<a href=\"services.html#service-2\" style=\"font-size: 0.85rem;\">OTA Management</a>": "<a href=\"services.html#service-2\" style=\"font-size: 0.85rem;\">การจัดการ OTA</a>",
  "<a href=\"services.html#service-3\" style=\"font-size: 0.85rem;\">PMS &amp; Channel Manager</a>": "<a href=\"services.html#service-3\" style=\"font-size: 0.85rem;\">PMS &amp; Channel Manager</a>",
  "<a href=\"services.html#service-4\" style=\"font-size: 0.85rem;\">Hotel Website Development</a>": "<a href=\"services.html#service-4\" style=\"font-size: 0.85rem;\">การพัฒนาเว็บไซต์โรงแรม</a>",
  "<a href=\"services.html#service-5\" style=\"font-size: 0.85rem;\">Hotel Digital Marketing</a>": "<a href=\"services.html#service-5\" style=\"font-size: 0.85rem;\">การตลาดดิจิทัลสำหรับโรงแรม</a>",
  "<a href=\"services.html#service-6\" style=\"font-size: 0.85rem;\">Reservations Management</a>": "<a href=\"services.html#service-6\" style=\"font-size: 0.85rem;\">การจัดการการจอง</a>",
  "<a href=\"services.html#service-7\" style=\"font-size: 0.85rem;\">Centralized Call Handling</a>": "<a href=\"services.html#service-7\" style=\"font-size: 0.85rem;\">การรับสายแบบรวมศูนย์</a>",
  "<a href=\"services.html#service-8\" style=\"font-size: 0.85rem;\">Guest Support</a>": "<a href=\"services.html#service-8\" style=\"font-size: 0.85rem;\">การสนับสนุนลูกค้า</a>",
  "<a href=\"services.html#service-9\" style=\"font-size: 0.85rem;\">Upselling &amp; Cross-Selling</a>": "<a href=\"services.html#service-9\" style=\"font-size: 0.85rem;\">การเพิ่มยอดขายและขายข้ามผลิตภัณฑ์</a>",
  "<svg fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewbox=\"0 0 24 24\"><path d=\"M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z\"></path><polyline points=\"22,6 12,13 2,6\"></polyline></svg>\n<a data-i18n=\"contact-info-email\" href=\"mailto:info@crscentral.com\">info@crscentral.com</a>": "<svg fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewbox=\"0 0 24 24\"><path d=\"M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z\"></path><polyline points=\"22,6 12,13 2,6\"></polyline></svg>\n<a data-i18n=\"contact-info-email\" href=\"mailto:info@crscentral.com\">info@crscentral.com</a>",
  "<svg fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewbox=\"0 0 24 24\"><path d=\"M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg>\n<span style=\"font-size: 0.8rem;\">Sri Sai Anurag New Town, Karimnagar–Hyderabad Highway, Secunderabad, Telangana 500078, India</span>": "<svg fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewbox=\"0 0 24 24\"><path d=\"M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z\"></path><circle cx=\"12\" cy=\"10\" r=\"3\"></circle></svg>\n<span style=\"font-size: 0.8rem;\">Sri Sai Anurag New Town, Karimnagar–Hyderabad Highway, Secunderabad, Telangana 500078, India</span>",
  "English": "อังกฤษ",
  "3. PMS, Channel Manager &amp; Booking Engine – Enterprise-Grade Hotel Software at an Independent-Hotel Price": "3. PMS, Channel Manager และระบบจองห้องพัก – ซอฟต์แวร์โรงแรมระดับองค์กรในราคาสำหรับโรงแรมอิสระ",
  "6. Reservations Management – Precision, Efficiency, and a Seamless Guest Experience": "6. การจัดการการจอง – แม่นยำ มีประสิทธิภาพ และประสบการณ์ที่ราบรื่นสำหรับแขก",
  "7. Centralized Call Handling – Professional, Brand-Aligned, and Always Available": "7. การรับสายแบบรวมศูนย์ – เป็นมืออาชีพ สอดคล้องกับแบรนด์ และพร้อมให้บริการเสมอ",
  "8. Guest Support – Extending Your Hospitality Beyond the Front Desk": "8. การสนับสนุนลูกค้า – ขยายการต้อนรับของคุณให้ไกลกว่าแค่แผนกต้อนรับ",
  "9. Upselling &amp; Cross-Selling – Maximizing Every Guest Interaction": "9. การเพิ่มยอดขายและขายข้ามผลิตภัณฑ์ – ใช้ประโยชน์สูงสุดจากทุกการปฏิสัมพันธ์กับแขก",
  "Running an independent hotel shouldn't mean paying enterprise software fees to keep your rooms synced across booking channels. StayCRS gives you a fully cloud-based Property Management System, Channel Manager, and a direct Booking Engine — the exact category of tools five-star chains rely on.": "การบริหารโรงแรมอิสระไม่ควรหมายถึงการต้องจ่ายค่าซอฟต์แวร์ระดับองค์กรเพื่อให้ห้องพักของคุณตรงกันในทุกช่องทางการจอง StayCRS มอบระบบจัดการทรัพย์สินบนคลาวด์เต็มรูปแบบ Channel Manager และระบบจองห้องพักโดยตรง — ซึ่งเป็นเครื่องมือประเภทเดียวกับที่เครือโรงแรมห้าดาวไว้วางใจ",
  "Manage reservations, room inventory, rates, and availability from one dashboard. With real-time two-way sync to Booking.com, Agoda, Expedia, Trip.com, and every major OTA, there are no double bookings, no manual rate updates, and no spreadsheets. Plus, steer more guests to your Booking Engine, where you only pay a flat 8% fee instead of 18%.": "จัดการการจอง จำนวนห้องพัก ราคา และความพร้อมให้บริการจากแดชบอร์ดเดียว ด้วยการซิงค์แบบสองทางเรียลไทม์กับ Booking.com, Agoda, Expedia, Trip.com และ OTA รายใหญ่ทุกราย จะไม่มีการจองซ้อน ไม่มีการอัปเดตราคาด้วยตนเอง และไม่ต้องใช้สเปรดชีต นอกจากนี้ยังสามารถดึงแขกมาที่ระบบจองของคุณมากขึ้น โดยเสียค่าธรรมเนียมคงที่เพียง 8% แทนที่จะเป็น 18%",
  "Most independent hotels either overpay for enterprise PMS platforms or make do with outdated, disconnected systems. StayCRS closes that gap — professional-grade hotel technology, priced for independent hotels.": "โรงแรมอิสระส่วนใหญ่มักจ่ายเงินแพงเกินไปสำหรับแพลตฟอร์ม PMS ระดับองค์กร หรือทนใช้ระบบที่ล้าสมัยและไม่เชื่อมต่อกัน StayCRS มาอุดช่องโหว่นั้น — เทคโนโลยีโรงแรมระดับมืออาชีพในราคาสำหรับโรงแรมอิสระ",
  "Get StayCRS From $110/Month →": "รับ StayCRS เริ่มต้นที่ $110/เดือน →",
  "Cloud PMS: Bookings, check-in/check-out, housekeeping status, and guest folios in one system, accessible from any device.": "Cloud PMS: การจอง เช็คอิน/เช็คเอาท์ สถานะแม่บ้าน และข้อมูลลูกค้าในระบบเดียว เข้าถึงได้จากทุกอุปกรณ์",
  "Channel Manager: Real-time rate and availability sync across all connected OTAs — update once, publish everywhere.": "Channel Manager: ซิงค์ราคาและความพร้อมให้บริการแบบเรียลไทม์ผ่าน OTA ที่เชื่อมต่อทั้งหมด — อัปเดตครั้งเดียว แสดงผลทุกที่",
  "Booking Engine: A better channel mix with a direct booking platform taking flat 8% fees.": "ระบบจอง: ส่วนผสมของช่องทางที่ดีกว่าด้วยแพลตฟอร์มการจองตรงที่คิดค่าธรรมเนียมคงที่ 8%",
  "No Setup Fee: Get live in days, not weeks, with no onboarding cost.": "ไม่มีค่าติดตั้ง: เปิดใช้งานได้ในไม่กี่วัน ไม่ใช่หลายสัปดาห์ โดยไม่มีค่าใช้จ่ายในการเริ่มต้น",
  "No Long-Term Lock-In: Transparent monthly pricing starting at $110/month, scaled to your hotel's size.": "ไม่มีข้อผูกมัดระยะยาว: ราคาโปร่งใสรายเดือนเริ่มต้นที่ $110/เดือน ปรับตามขนาดโรงแรมของคุณ",
  "Seamless CRS Central Integration: Because we also run your revenue management, your pricing strategy and your booking system stay perfectly in sync.": "การบูรณาการเข้ากับ CRS Central อย่างราบรื่น: เนื่องจากเราดูแลการจัดการรายได้ของคุณ กลยุทธ์ราคาและระบบการจองของคุณจึงประสานงานกันอย่างสมบูรณ์",
  "The CRS Central Advantage in Thailand": "ข้อได้เปรียบของ CRS Central ในประเทศไทย",
  "Why Bangkok Hotels Need Revenue Management Now": "ทำไมโรงแรมในกรุงเทพฯ จึงต้องมีการจัดการรายได้ตอนนี้",
  "What CRS Central Does for Bangkok Hotels": "CRS Central ทำอะไรให้กับโรงแรมในกรุงเทพฯ",
  "Why Hua Hin Hotels Need Revenue Management Now": "ทำไมโรงแรมในหัวหินจึงต้องมีการจัดการรายได้ตอนนี้",
  "What CRS Central Does for Hua Hin Hotels": "CRS Central ทำอะไรให้กับโรงแรมในหัวหิน",
  "Why Pattaya Hotels Need Revenue Management Now": "ทำไมโรงแรมในพัทยาจึงต้องมีการจัดการรายได้ตอนนี้",
  "What CRS Central Does for Pattaya Hotels": "CRS Central ทำอะไรให้กับโรงแรมในพัทยา",
  "Why Phuket Hotels Need Revenue Management Now": "ทำไมโรงแรมในภูเก็ตจึงต้องมีการจัดการรายได้ตอนนี้",
  "What CRS Central Does for Phuket Hotels": "CRS Central ทำอะไรให้กับโรงแรมในภูเก็ต",
  "A Stronger Pricing Structure": "โครงสร้างราคาที่แข็งแกร่งยิ่งขึ้น",
  "Better Revenue Control": "การควบคุมรายได้ที่ดีขึ้น",
  "Lower Commission Costs": "ต้นทุนค่าคอมมิชชั่นที่ลดลง",
  "Long-Term Growth": "การเติบโตในระยะยาว",
  "Bangkok is a year-round hotel market. Business travellers, meetings and events, medical visitors, transit stays and city-break tourists all fill rooms, from Sukhumvit and Silom to the riverside and Old City. With thousands of rooms competing in every price band, the hotels that win are the ones that price with discipline.": "กรุงเทพฯ เป็นตลาดโรงแรมที่มีผู้เข้าพักตลอดปี ทั้งนักเดินทางเพื่อธุรกิจ การประชุมและงานอีเวนต์ ผู้มาเยือนเพื่อการแพทย์ ผู้โดยสารต่อเครื่อง และนักท่องเที่ยวพักผ่อนในเมืองต่างก็เติมเต็มห้องพัก ตั้งแต่สุขุมวิทและสีลมไปจนถึงริมแม่น้ำและเขตเมืองเก่า ด้วยห้องพักหลายพันห้องที่แข่งขันกันในทุกช่วงราคา โรงแรมที่ชนะคือโรงแรมที่มีการตั้งราคาอย่างมีระเบียบวินัย",
  "Hua Hin is a classic seaside resort town within easy reach of Bangkok. Its demand is shaped by weekend and holiday visitors from the capital, golf, family travel and wellness stays, plus guests who spend extended periods in the cool season. That makes demand highly uneven across the week and the year.": "หัวหินเป็นเมืองตากอากาศริมทะเลยอดนิยมที่เดินทางจากกรุงเทพฯ ได้ง่าย อุปสงค์เกิดจากผู้มาเยือนในช่วงสุดสัปดาห์และวันหยุดจากเมืองหลวง กอล์ฟ การเดินทางแบบครอบครัว และการเข้าพักเพื่อสุขภาพ รวมถึงแขกที่พักระยะยาวในช่วงฤดูหนาว ทำให้ความต้องการไม่สม่ำเสมออย่างมากตลอดทั้งสัปดาห์และตลอดปี",
  "Pattaya combines drive-in weekend demand from Bangkok and the eastern region with regional and international leisure travellers, groups, weddings and events. Its large supply of rooms and strong OTA presence make rate discipline and channel mix especially important.": "พัทยารวมความต้องการในช่วงสุดสัปดาห์ที่ขับรถจากกรุงเทพฯ และภูมิภาคตะวันออกเข้ากับนักท่องเที่ยวที่มาพักผ่อนทั้งในและต่างประเทศ กลุ่มทัวร์ งานแต่งงาน และอีเวนต์ ด้วยจำนวนห้องพักจำนวนมากและอิทธิพลของ OTA ที่แข็งแกร่ง ทำให้วินัยด้านราคาและส่วนผสมของช่องทางมีความสำคัญอย่างยิ่ง",
  "Phuket is Thailand's best-known island destination, with beach resorts, boutique hotels and private villas serving international guests across Patong, Kata, Karon, Kamala, Bang Tao and Phuket Town. Demand swings sharply between the high season and the quieter monsoon months, and many guests book far in advance.": "ภูเก็ตเป็นจุดหมายปลายทางเกาะที่มีชื่อเสียงที่สุดของไทย ด้วยรีสอร์ทริมหาด โรงแรมบูติก และวิลล่าส่วนตัวที่ให้บริการแขกต่างชาติทั่วทั้งป่าตอง กะตะ กะรน กมลา บางเทา และตัวเมืองภูเก็ต อุปสงค์จะแกว่งอย่างรวดเร็วระหว่างช่วงไฮซีซั่นและช่วงมรสุมที่เงียบกว่า และแขกจำนวนมากจองล่วงหน้าเป็นเวลานาน",
  "Hotels that partner with CRS Central typically see a 10% to 40% improvement in revenue performance, depending on market conditions, current positioning and operational setup.": "โรงแรมที่เป็นพันธมิตรกับ CRS Central มักจะเห็นรายได้ดีขึ้น 10% ถึง 40% ขึ้นอยู่กับสภาพตลาด ตำแหน่งทางการตลาดในปัจจุบัน และโครงสร้างการดำเนินงาน",
  "Rates that reflect demand rather than guesswork.": "ราคาที่สะท้อนถึงอุปสงค์มากกว่าการคาดเดา",
  "Clear visibility into revenue sources, channel performance and leakage.": "มองเห็นแหล่งที่มาของรายได้ ประสิทธิภาพของช่องทาง และการรั่วไหลได้อย่างชัดเจน",
  "A better channel mix with more bookings won directly.": "ส่วนผสมของช่องทางที่ดีกว่าและได้รับการจองตรงมากขึ้น",
  "A scalable foundation that supports sustained improvement across seasons.": "รากฐานที่ปรับขนาดได้ซึ่งสนับสนุนการปรับปรุงอย่างยั่งยืนในทุกฤดูกาล",
  "Thailand rewards hotels that manage seasons, channels and rates with discipline. We bring the commercial strategies of international hotel chains to independent hotels and villas, and we work as your extended revenue team, not an external agency.": "ประเทศไทยให้รางวัลแก่โรงแรมที่จัดการฤดูกาล ช่องทาง และราคาอย่างมีวินัย เรานำกลยุทธ์ทางการค้าของเครือโรงแรมระดับนานาชาติมาสู่โรงแรมและวิลล่าอิสระ และเราทำงานเป็นทีมรายได้ที่ขยายออกไปของคุณ ไม่ใช่หน่วยงานภายนอก",
  "We work with hotels, resorts and villas in Bangkok, Hua Hin, Pattaya and Phuket.": "เราทำงานร่วมกับโรงแรม รีสอร์ท และวิลล่าในกรุงเทพฯ หัวหิน พัทยา และภูเก็ต",
  "No. We work inside your existing PMS and channel manager. If you want one connected system, StayCRS offers a PMS, Channel Manager and Booking Engine.": "ไม่ เราทำงานภายใน PMS และ Channel Manager ที่คุณมีอยู่แล้ว หากคุณต้องการระบบเดียวที่เชื่อมต่อถึงกัน StayCRS มีทั้ง PMS, Channel Manager และระบบจองห้องพัก",
  "You pay a flat monthly fee with no commission on your bookings and no setup fee. Contact us for a quote based on your property.": "คุณจ่ายค่าธรรมเนียมรายเดือนคงที่โดยไม่มีค่าคอมมิชชั่นจากการจองและไม่มีค่าธรรมเนียมติดตั้ง ติดต่อเราเพื่อขอใบเสนอราคาตามอสังหาริมทรัพย์ของคุณ",
  "From a 20-room boutique to a 200-room resort or villa collection.": "ตั้งแต่โรงแรมบูติกขนาด 20 ห้องไปจนถึงรีสอร์ท 200 ห้องหรือกลุ่มวิลล่า",
  "A complimentary 20 to 30 minute review of your pricing, OTA performance, competitor positioning and distribution setup, with no obligation.": "ตรวจทานราคา ประสิทธิภาพบน OTA ตำแหน่งคู่แข่ง และการตั้งค่าช่องทางจำหน่ายของคุณฟรี 20 ถึง 30 นาที โดยไม่มีข้อผูกมัด",
  "See StayCRS PMS, Channel Manager and Booking Engine →": "ดู StayCRS PMS, Channel Manager และระบบจองห้องพัก →",
  "<svg viewbox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><title>Thailand Market Expertise — CRS Central</title><path d=\"M19.365 9.863c.349 0 .63.285.63.631 0 .345-.281.63-.63.63H17.61v1.125h1.755c.349 0 .63.283.63.63 0 .344-.281.629-.63.629h-2.386c-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63h2.386c.346 0 .627.285.627.63 0 .349-.281.63-.63.63H17.61v1.125h1.755zm-3.855 3.016c0 .27-.174.51-.432.596-.064.021-.133.031-.199.031-.211 0-.391-.09-.51-.25l-2.443-3.317v2.94c0 .344-.279.629-.631.629-.346 0-.626-.285-.626-.629V8.108c0-.27.173-.51.43-.595.06-.023.136-.033.194-.033.195 0 .375.104.495.254l2.462 3.33V8.108c0-.345.282-.63.63-.63.345 0 .63.285.63.63v4.771zm-5.741 0c0 .344-.282.629-.631.629-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63.346 0 .628.285.628.63v4.771zm-2.466.629H4.917c-.345 0-.63-.285-.63-.629V8.108c0-.345.285-.63.63-.63.348 0 .63.285.63.63v4.141h1.756c.348 0 .629.283.629.63 0 .344-.282.629-.629.629M24 10.314C24 4.943 18.615.572 12 .572S0 4.943 0 10.314c0 4.811 4.27 8.842 10.035 9.608.391.082.923.258 1.058.59.12.301.079.766.038 1.08l-.164 1.02c-.045.301-.24 1.186 1.049.645 1.291-.539 6.916-4.078 9.436-6.975C23.176 14.393 24 12.458 24 10.314\"></path></svg>": "<svg viewbox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><title>Thailand Market Expertise — CRS Central</title><path d=\"M19.365 9.863c.349 0 .63.285.63.631 0 .345-.281.63-.63.63H17.61v1.125h1.755c.349 0 .63.283.63.63 0 .344-.281.629-.63.629h-2.386c-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63h2.386c.346 0 .627.285.627.63 0 .349-.281.63-.63.63H17.61v1.125h1.755zm-3.855 3.016c0 .27-.174.51-.432.596-.064.021-.133.031-.199.031-.211 0-.391-.09-.51-.25l-2.443-3.317v2.94c0 .344-.279.629-.631.629-.346 0-.626-.285-.626-.629V8.108c0-.27.173-.51.43-.595.06-.023.136-.033.194-.033.195 0 .375.104.495.254l2.462 3.33V8.108c0-.345.282-.63.63-.63.345 0 .63.285.63.63v4.771zm-5.741 0c0 .344-.282.629-.631.629-.345 0-.627-.285-.627-.629V8.108c0-.345.282-.63.63-.63.346 0 .628.285.628.63v4.771zm-2.466.629H4.917c-.345 0-.63-.285-.63-.629V8.108c0-.345.285-.63.63-.63.348 0 .63.285.63.63v4.141h1.756c.348 0 .629.283.629.63 0 .344-.282.629-.629.629M24 10.314C24 4.943 18.615.572 12 .572S0 4.943 0 10.314c0 4.811 4.27 8.842 10.035 9.608.391.082.923.258 1.058.59.12.301.079.766.038 1.08l-.164 1.02c-.045.301-.24 1.186 1.049.645 1.291-.539 6.916-4.078 9.436-6.975C23.176 14.393 24 12.458 24 10.314\"></path></svg>",
  "<strong>Flat Weekday and Weekend Pricing:</strong> Rates do not reflect the very different demand on corporate weekdays and leisure weekends.": "<strong>ราคาที่คงที่ทั้งวันธรรมดาและวันหยุดสุดสัปดาห์:</strong> ราคาไม่ได้สะท้อนถึงความต้องการที่แตกต่างกันอย่างมากในวันธรรมดาสำหรับลูกค้าองค์กรและวันหยุดสุดสัปดาห์สำหรับผู้ที่มาพักผ่อน",
  "<strong>Crowded Competitive Sets:</strong> Hundreds of similar properties within a few streets make rate position and OTA ranking critical.": "<strong>กลุ่มคู่แข่งที่หนาแน่น:</strong> ที่พักที่คล้ายกันหลายร้อยแห่งในถนนเพียงไม่กี่เส้นทำให้การวางตำแหน่งราคาและอันดับบน OTA มีความสำคัญมาก",
  "<strong>OTA Dependency:</strong> Most bookings arrive through a handful of OTAs, creating heavy commission costs and little direct revenue.": "<strong>การพึ่งพา OTA อย่างมาก:</strong> การจองส่วนใหญ่มาจาก OTA เพียงไม่กี่ราย ทำให้เกิดต้นทุนค่าคอมมิชชั่นสูงและมีรายได้โดยตรงเพียงเล็กน้อย",
  "<strong>Untapped Segments:</strong> Corporate accounts, long-stay guests, event and meeting groups and medical visitors are present in Bangkok but rarely targeted strategically.": "<strong>กลุ่มลูกค้าที่ยังไม่ได้รับการเข้าถึง:</strong> ลูกค้าองค์กร แขกที่พักระยะยาว กลุ่มจัดงานอีเวนต์และการประชุม และผู้มาใช้บริการทางการแพทย์มีอยู่ในกรุงเทพฯ แต่มักไม่ค่อยตกเป็นเป้าหมายเชิงกลยุทธ์",
  "<strong>Dynamic Pricing by Day and Segment:</strong> Rate structures that respond to weekday corporate demand, weekend leisure, events and competitor moves.": "<strong>การกำหนดราคายืดหยุ่นตามวันและกลุ่มลูกค้า:</strong> โครงสร้างราคาที่ตอบสนองความต้องการขององค์กรในวันธรรมดา การพักผ่อนในวันหยุดสุดสัปดาห์ กิจกรรม และความเคลื่อนไหวของคู่แข่ง",
  "<strong>Competitive Set Monitoring:</strong> Clear rate positioning against the properties your guests actually compare you with.": "<strong>การติดตามกลุ่มคู่แข่ง:</strong> ตำแหน่งราคาที่ชัดเจนเมื่อเทียบกับที่พักที่แขกของคุณเปรียบเทียบด้วยจริงๆ",
  "<strong>OTA Performance Improvement:</strong> Better content, smarter promotions and stronger conversion on Agoda, Booking.com, Trip.com and Expedia.": "<strong>การปรับปรุงประสิทธิภาพ OTA:</strong> เนื้อหาที่ดีกว่า โปรโมชั่นที่ชาญฉลาดกว่า และการเปลี่ยนเป็นยอดจองที่แข็งแกร่งขึ้นบน Agoda, Booking.com, Trip.com และ Expedia",
  "<strong>Corporate and Long-Stay Strategy:</strong> Pricing and packages for negotiated accounts, extended stays and small groups.": "<strong>กลยุทธ์สำหรับลูกค้าองค์กรและการพักระยะยาว:</strong> ราคาและแพ็กเกจสำหรับบัญชีที่มีการเจรจา การเข้าพักแบบขยายเวลา และกลุ่มเล็ก",
  "<strong>Direct Booking Growth:</strong> Reducing OTA commission dependency through your website, phone, LINE and WhatsApp enquiries.": "<strong>การเติบโตของการจองตรง:</strong> ลดการพึ่งพาค่าคอมมิชชั่นของ OTA ผ่านการสอบถามทางเว็บไซต์ โทรศัพท์ LINE และ WhatsApp ของคุณ",
  "<strong>Weekend Peaks and Midweek Gaps:</strong> Rooms sell out at weekends and public holidays while midweek stays empty, often leading to broad discounting.": "<strong>จุดสูงสุดในวันหยุดสุดสัปดาห์และช่องว่างในช่วงกลางสัปดาห์:</strong> ห้องพักเต็มในช่วงวันหยุดสุดสัปดาห์และวันหยุดนักขัตฤกษ์ ในขณะที่ช่วงกลางสัปดาห์ว่างเปล่า ซึ่งมักนำไปสู่การลดราคาในวงกว้าง",
  "<strong>Last-Minute Booking Behaviour:</strong> Short-notice bookings from the Bangkok market make pricing and availability decisions time-sensitive.": "<strong>พฤติกรรมการจองในนาทีสุดท้าย:</strong> การจองล่วงหน้าในระยะสั้นจากตลาดกรุงเทพฯ ทำให้การตัดสินใจด้านราคาและจำนวนห้องว่างต้องแข่งกับเวลา",
  "<strong>Seasonal Long-Stay Demand:</strong> Longer stays in the cool season are often priced without a clear structure.": "<strong>อุปสงค์การเข้าพักระยะยาวตามฤดูกาล:</strong> การเข้าพักระยะยาวในช่วงฤดูหนาวมักมีราคาโดยไม่มีโครงสร้างที่ชัดเจน",
  "<strong>Limited Direct Distribution:</strong> Many properties depend on OTAs for guests who would book direct if the offer were clear.": "<strong>การจำหน่ายโดยตรงที่จำกัด:</strong> ที่พักหลายแห่งต้องพึ่งพา OTA สำหรับแขกที่อาจจะจองตรงหากข้อเสนอมีความชัดเจน",
  "<strong>Peak and Holiday Yield Protection:</strong> Rate tiers that capture full value on weekends and Thai public holidays.": "<strong>การป้องกันผลตอบแทนในช่วงพีคและวันหยุด:</strong> ระดับราคาที่สามารถจับมูลค่าเต็มที่ในช่วงวันหยุดสุดสัปดาห์และวันหยุดนักขัตฤกษ์ของไทย",
  "<strong>Midweek Demand Building:</strong> Offers and packages for golf, wellness, family and long-weekend stays that fill quiet nights without cutting rates across the board.": "<strong>การสร้างอุปสงค์ช่วงกลางสัปดาห์:</strong> ข้อเสนอและแพ็กเกจสำหรับการเล่นกอล์ฟ การดูแลสุขภาพ ครอบครัว และการพักผ่อนช่วงวันหยุดยาว ที่ช่วยเติมเต็มคืนที่เงียบเหงาโดยไม่ต้องลดราคาโดยรวม",
  "<strong>Long-Stay Rate Structure:</strong> Clear weekly and monthly pricing for seasonal visitors.": "<strong>โครงสร้างราคาสำหรับพักระยะยาว:</strong> ราคาที่ชัดเจนรายสัปดาห์และรายเดือนสำหรับผู้มาเยือนตามฤดูกาล",
  "<strong>OTA Optimization:</strong> Content, ranking and promotion improvements on the channels your Bangkok and international guests use.": "<strong>การปรับแต่ง OTA:</strong> การปรับปรุงเนื้อหา อันดับ และโปรโมชั่นในช่องทางที่แขกในกรุงเทพฯ และต่างประเทศของคุณใช้",
  "<strong>Direct Booking Development:</strong> A booking path through your website, LINE and WhatsApp for repeat weekend guests.": "<strong>การพัฒนาการจองตรง:</strong> เส้นทางการจองผ่านเว็บไซต์ LINE และ WhatsApp ของคุณสำหรับแขกที่กลับมาพักช่วงสุดสัปดาห์",
  "<strong>Heavy OTA Dependency:</strong> Bookings flow mostly through a few channels, creating large commission costs.": "<strong>การพึ่งพา OTA อย่างหนัก:</strong> การจองส่วนใหญ่มาจากไม่กี่ช่องทาง ทำให้เกิดต้นทุนค่าคอมมิชชั่นมหาศาล",
  "<strong>Rate Competition:</strong> Dense supply across every price level pushes hotels into price-led selling.": "<strong>การแข่งขันด้านราคา:</strong> อุปทานที่หนาแน่นในทุกระดับราคาผลักดันให้โรงแรมต้องขายด้วยการลดราคา",
  "<strong>Group and Event Pricing:</strong> Groups, weddings and events are often quoted without a yield-based approach.": "<strong>การกำหนดราคาสำหรับกลุ่มและอีเวนต์:</strong> กลุ่มลูกค้า งานแต่งงาน และอีเวนต์มักจะถูกเสนอราคาโดยไม่มีแนวทางที่อิงตามผลตอบแทน",
  "<strong>Weak Weekend and Holiday Capture:</strong> Peak nights are sold too cheaply and too early.": "<strong>การจับยอดในช่วงสุดสัปดาห์และวันหยุดที่อ่อนแอ:</strong> คืนที่มีผู้เข้าพักมากถูกขายในราคาถูกเกินไปและเร็วเกินไป",
  "<strong>Rate Integrity and Parity:</strong> Consistent rates across every channel, with controls that stop uncontrolled discounting.": "<strong>ความสมบูรณ์และความเท่าเทียมของราคา:</strong> ราคาที่สอดคล้องกันในทุกช่องทาง พร้อมการควบคุมที่หยุดยั้งการลดราคาที่ไม่สามารถควบคุมได้",
  "<strong>Group and Event Strategy:</strong> Pricing frameworks that account for displaced transient demand and group value.": "<strong>กลยุทธ์สำหรับกลุ่มและอีเวนต์:</strong> กรอบการตั้งราคาที่คำนึงถึงอุปสงค์ชั่วคราวที่ถูกแทนที่และมูลค่าของกลุ่ม",
  "<strong>OTA Visibility and Conversion:</strong> Better listings, smarter promotions and the right mix of channels.": "<strong>การมองเห็นและอัตราคอนเวอร์ชันบน OTA:</strong> รายการที่พักที่ดีกว่า โปรโมชั่นที่ชาญฉลาดกว่า และส่วนผสมช่องทางที่เหมาะสม",
  "<strong>Weekend and Holiday Yield:</strong> Rate tiers and minimum-stay rules for peak periods.": "<strong>ผลตอบแทนในช่วงสุดสัปดาห์และวันหยุด:</strong> ระดับราคาและกฎการเข้าพักขั้นต่ำสำหรับช่วงที่มีความต้องการสูง",
  "<strong>Commission Reduction:</strong> A direct booking strategy supported by the StayCRS Booking Engine.": "<strong>การลดค่าคอมมิชชั่น:</strong> กลยุทธ์การจองตรงที่สนับสนุนโดยระบบจอง StayCRS",
  "<strong>Sharp Season Swings:</strong> High-season rates are often under-priced, while low-season rooms are discounted too deeply.": "<strong>การแกว่งตัวของฤดูกาลที่รุนแรง:</strong> ราคาช่วงไฮซีซั่นมักจะตั้งไว้ต่ำเกินไป ในขณะที่ห้องพักช่วงโลว์ซีซั่นถูกลดราคามากเกินไป",
  "<strong>Booking Window Pressure:</strong> Long-haul guests book early, so early-season pricing decisions affect the whole year.": "<strong>แรงกดดันในช่วงเวลาการจอง:</strong> แขกที่เดินทางไกลมักจองล่วงหน้า การตัดสินใจด้านราคาในช่วงต้นฤดูกาลจึงส่งผลกระทบต่อทั้งปี",
  "<strong>Villa and Resort Complexity:</strong> Villas, suites and room types need separate pricing logic, minimum stays and seasonal rules.": "<strong>ความซับซ้อนของวิลล่าและรีสอร์ท:</strong> วิลล่า ห้องสวีท และประเภทห้องต้องการตรรกะการตั้งราคาที่แยกจากกัน จำนวนคืนที่เข้าพักขั้นต่ำ และกฎตามฤดูกาล",
  "<strong>High OTA Commissions:</strong> Premium rates mean every point of commission has a large impact.": "<strong>ค่าคอมมิชชั่น OTA ที่สูง:</strong> ราคาพรีเมียมหมายความว่าทุกจุดของคอมมิชชั่นมีผลกระทบมาก",
  "<strong>High-Season Yield Protection:</strong> Structured rate tiers and minimum-stay rules that capture full value at peak.": "<strong>การป้องกันผลตอบแทนช่วงไฮซีซั่น:</strong> ระดับราคาที่มีโครงสร้างและกฎการเข้าพักขั้นต่ำที่จับมูลค่าได้เต็มที่ในช่วงที่มีความต้องการสูง",
  "<strong>Low-Season Strategy:</strong> Demand-building offers and packages that protect rate integrity rather than discounting broadly.": "<strong>กลยุทธ์ช่วงโลว์ซีซั่น:</strong> ข้อเสนอและแพ็กเกจการสร้างอุปสงค์ที่ปกป้องความสมบูรณ์ของราคามากกว่าการลดราคาในวงกว้าง",
  "<strong>Villa and Room-Type Pricing:</strong> Clear logic across villas, suites and room categories, including long-stay rates.": "<strong>การตั้งราคาของวิลล่าและประเภทห้อง:</strong> ตรรกะที่ชัดเจนในวิลล่า ห้องสวีท และประเภทห้องพัก รวมถึงราคาสำหรับการพักระยะยาว",
  "<strong>International OTA Optimization:</strong> Content and ranking improvements on Booking.com, Agoda, Trip.com and Expedia.": "<strong>การปรับแต่ง OTA ระดับนานาชาติ:</strong> การปรับปรุงเนื้อหาและอันดับใน Booking.com, Agoda, Trip.com และ Expedia",
  "<strong>Direct Booking Development:</strong> Reducing commission dependency for a market where high rates make direct conversion especially valuable.": "<strong>การพัฒนาการจองตรง:</strong> การลดการพึ่งพาคอมมิชชั่นสำหรับตลาดที่อัตราค่าห้องสูงทำให้การเปลี่ยนเป็นการจองตรงมีค่าอย่างยิ่ง",
  "<strong>Hotel-Operator Experience:</strong> Our leadership has run five-star hotels, so our strategies are data-driven and operationally realistic.": "<strong>ประสบการณ์ผู้ประกอบการโรงแรม:</strong> ผู้นำของเราเคยบริหารโรงแรมห้าดาว ดังนั้นกลยุทธ์ของเราจึงขับเคลื่อนด้วยข้อมูลและใช้งานได้จริงในเชิงปฏิบัติ",
  "<strong>Thai OTA Landscape:</strong> Day-to-day management across Agoda, Booking.com, Trip.com, Expedia and Traveloka.": "<strong>ภูมิทัศน์ของ OTA ในไทย:</strong> การจัดการรายวันครอบคลุม Agoda, Booking.com, Trip.com, Expedia และ Traveloka",
  "<strong>One Connected System:</strong> StayCRS PMS, Channel Manager and Booking Engine, with a flat 8% on direct bookings against around 18% through an OTA.": "<strong>ระบบที่เชื่อมต่อเป็นหนึ่งเดียว:</strong> StayCRS PMS, Channel Manager และ Booking Engine พร้อมคิดค่าธรรมเนียมการจองตรงคงที่ 8% เทียบกับประมาณ 18% ผ่าน OTA",
  "<strong>Easy Communication:</strong> Support by LINE, WhatsApp and email, with transparent reporting and no hidden fees.": "<strong>การสื่อสารที่ง่ายดาย:</strong> การสนับสนุนทาง LINE, WhatsApp และอีเมล พร้อมการรายงานที่โปร่งใสและไม่มีค่าธรรมเนียมแอบแฝง",
  "Flat Weekday and Weekend Pricing:": "ราคาคงที่วันธรรมดาและวันหยุดสุดสัปดาห์:",
  "Crowded Competitive Sets:": "กลุ่มคู่แข่งที่หนาแน่น:",
  "OTA Dependency:": "การพึ่งพา OTA:",
  "Untapped Segments:": "กลุ่มลูกค้าที่ยังไม่ได้เข้าถึง:",
  "Dynamic Pricing by Day and Segment:": "การกำหนดราคายืดหยุ่นตามวันและกลุ่มเป้าหมาย:",
  "Competitive Set Monitoring:": "การติดตามกลุ่มคู่แข่ง:",
  "OTA Performance Improvement:": "การปรับปรุงประสิทธิภาพ OTA:",
  "Corporate and Long-Stay Strategy:": "กลยุทธ์ลูกค้าองค์กรและการพักระยะยาว:",
  "Direct Booking Growth:": "การเติบโตของการจองตรง:",
  "Weekend Peaks and Midweek Gaps:": "ช่วงพีควันหยุดสุดสัปดาห์และช่องว่างกลางสัปดาห์:",
  "Last-Minute Booking Behaviour:": "พฤติกรรมการจองนาทีสุดท้าย:",
  "Seasonal Long-Stay Demand:": "ความต้องการพักระยะยาวตามฤดูกาล:",
  "Limited Direct Distribution:": "การจำหน่ายโดยตรงมีจำกัด:",
  "Peak and Holiday Yield Protection:": "การปกป้องรายได้ช่วงพีคและวันหยุด:",
  "Midweek Demand Building:": "การสร้างอุปสงค์ช่วงกลางสัปดาห์:",
  "Long-Stay Rate Structure:": "โครงสร้างราคาที่พักระยะยาว:",
  "OTA Optimization:": "การปรับแต่ง OTA:",
  "Direct Booking Development:": "การพัฒนาการจองตรง:",
  "Heavy OTA Dependency:": "พึ่งพา OTA สูง:",
  "Rate Competition:": "การแข่งขันด้านราคา:",
  "Group and Event Pricing:": "การกำหนดราคากลุ่มและอีเวนต์:",
  "Weak Weekend and Holiday Capture:": "การทำยอดช่วงวันหยุดและสุดสัปดาห์อ่อนแอ:",
  "Rate Integrity and Parity:": "ความสมบูรณ์และสมดุลของราคา:",
  "Group and Event Strategy:": "กลยุทธ์สำหรับกลุ่มและอีเวนต์:",
  "OTA Visibility and Conversion:": "การมองเห็นและการแปลงยอดบน OTA:",
  "Weekend and Holiday Yield:": "ผลตอบแทนช่วงวันหยุดและสุดสัปดาห์:",
  "Commission Reduction:": "การลดค่าคอมมิชชั่น:",
  "Sharp Season Swings:": "ความผันผวนตามฤดูกาลสูง:",
  "Booking Window Pressure:": "แรงกดดันของช่วงเวลาการจอง:",
  "Villa and Resort Complexity:": "ความซับซ้อนของวิลล่าและรีสอร์ท:",
  "High OTA Commissions:": "ค่าคอมมิชชั่น OTA สูง:",
  "High-Season Yield Protection:": "การปกป้องผลตอบแทนช่วงไฮซีซั่น:",
  "Low-Season Strategy:": "กลยุทธ์ช่วงโลว์ซีซั่น:",
  "Villa and Room-Type Pricing:": "การตั้งราคาวิลล่าและประเภทห้อง:",
  "International OTA Optimization:": "การปรับแต่ง OTA ในระดับนานาชาติ:",
  "Hotel-Operator Experience:": "ประสบการณ์บริหารโรงแรม:",
  "Thai OTA Landscape:": "ภาพรวม OTA ในประเทศไทย:",
  "One Connected System:": "ระบบที่เชื่อมต่อเป็นหนึ่งเดียว:",
  "Easy Communication:": "การสื่อสารง่าย:",
  "Bangkok": "กรุงเทพฯ",
  "Corporate, events and meetings, city breaks, medical and long-stay guests": "องค์กร, อีเวนต์และการประชุม, วันหยุดพักผ่อนในเมือง, แขกเชิงการแพทย์ และแขกพักระยะยาว",
  "Weekday corporate demand year-round, leisure peak in the cool season": "อุปสงค์จากองค์กรในวันธรรมดาตลอดทั้งปี, จุดสูงสุดของการพักผ่อนในฤดูหนาว",
  "Weekday and weekend pricing, rate parity, weak direct booking": "ราคาในวันธรรมดาและวันหยุดสุดสัปดาห์, ความเท่าเทียมกันของราคา, การจองตรงที่อ่อนแอ",
  "Hua Hin": "หัวหิน",
  "Bangkok weekend and holiday visitors, golf, families, wellness, long-stay seasonal guests": "ผู้มาเยือนจากกรุงเทพฯ ในช่วงสุดสัปดาห์และวันหยุด, กอล์ฟ, ครอบครัว, สุขภาพ, แขกพักระยะยาวตามฤดูกาล",
  "Weekends, Thai public holidays, cool season": "วันหยุดสุดสัปดาห์, วันหยุดนักขัตฤกษ์ไทย, ฤดูหนาว",
  "Low midweek occupancy, last-minute discounting": "อัตราการเข้าพักกลางสัปดาห์ต่ำ, การลดราคานาทีสุดท้าย",
  "Pattaya": "พัทยา",
  "Drive-in weekend guests, regional and international leisure, groups, weddings and events": "แขกขับรถมาพักวันหยุดสุดสัปดาห์, นักท่องเที่ยวในภูมิภาคและต่างประเทศ, กลุ่มทัวร์, งานแต่งงาน และอีเวนต์",
  "Weekends, holidays, high season": "วันหยุดสุดสัปดาห์, วันหยุดยาว, ไฮซีซั่น",
  "Heavy OTA dependency, group and event pricing": "พึ่งพา OTA อย่างหนัก, การตั้งราคากลุ่มและอีเวนต์",
  "Phuket": "ภูเก็ต",
  "International beach holidays, resorts, villas and long stays": "วันหยุดพักผ่อนริมหาดระดับนานาชาติ, รีสอร์ท, วิลล่า และการพักระยะยาว",
  "High season from late year to spring, quieter monsoon months": "ไฮซีซั่นตั้งแต่ปลายปีถึงฤดูใบไม้ผลิ, เดือนมรสุมที่เงียบเหงากว่า",
  "Season swings, villa pricing, high commissions": "ความผันผวนของฤดูกาล, การตั้งราคาวิลล่า, ค่าคอมมิชชั่นที่สูง",
  "City": "เมือง",
  "Main demand": "อุปสงค์หลัก",
  "Peak periods": "ช่วงพีค",
  "Typical revenue gap": "ช่องว่างของรายได้ทั่วไป",
  "Senior Leadership": "ผู้บริหารระดับสูง",
  "N S Chauhan": "N S Chauhan",
  "Poonam D": "Poonam D",
  "S Chauhan": "S Chauhan",
  "<strong style=\"color: var(--accent-color);\">Vision:</strong> <span data-i18n=\"about-vision-desc\">To become the most trusted global revenue management partner for independent hotels — enabling them to compete confidently with large hotel chains.</span>": "<strong style=\"color: var(--accent-color);\">วิสัยทัศน์:</strong> <span data-i18n=\"about-vision-desc\">เพื่อเป็นพันธมิตรด้านการจัดการรายได้ระดับโลกที่ได้รับความไว้วางใจสูงสุดสำหรับโรงแรมอิสระ — ช่วยให้พวกเขาสามารถแข่งขันได้อย่างมั่นใจกับเครือโรงแรมขนาดใหญ่</span>",
  "<strong style=\"color: var(--accent-color);\">Mission:</strong> <span data-i18n=\"about-mission-desc\">To empower independent hotels and resorts to increase revenue, optimize operations, and elevate guest satisfaction through brand-aligned solutions.</span>": "<strong style=\"color: var(--accent-color);\">พันธกิจ:</strong> <span data-i18n=\"about-mission-desc\">เพื่อเสริมสร้างศักยภาพให้โรงแรมและรีสอร์ทอิสระในการเพิ่มรายได้ เพิ่มประสิทธิภาพการดำเนินงาน และยกระดับความพึงพอใจของแขกผ่านโซลูชันที่สอดคล้องกับแบรนด์</span>",
  "Managing Director &amp; Founder": "กรรมการผู้จัดการและผู้ก่อตั้ง",
  "Former 5-Star Hotel General Manager with decades of commercial yield experience in Thailand, Laos, India, Nepal, Malaysia and Vietnam.": "อดีตผู้จัดการทั่วไปโรงแรมระดับ 5 ดาว ที่มีประสบการณ์ด้านผลตอบแทนเชิงพาณิชย์ยาวนานหลายทศวรรษในประเทศไทย ลาว อินเดีย เนปาล มาเลเซีย และเวียดนาม",
  "Head of Revenue Strategy": "หัวหน้าฝ่ายกลยุทธ์รายได้",
  "Dynamic pricing specialist and OTA systems expert. Formerly managed regional portfolios for luxury chains.": "ผู้เชี่ยวชาญด้านราคายืดหยุ่นและระบบ OTA อดีตผู้บริหารพอร์ตโฟลิโอระดับภูมิภาคสำหรับเครือโรงแรมหรู",
  "Director of Operations": "ผู้อำนวยการฝ่ายปฏิบัติการ",
  "Oversees centralized call handling, reservations integrations, and guest support teams across Vietnam &amp; South Asia.": "ดูแลการรับสายแบบรวมศูนย์ การทำงานร่วมกันของการจอง และทีมสนับสนุนลูกค้าทั่วเวียดนามและเอเชียใต้",
  "Company Profile - EN": "โปรไฟล์บริษัท - EN",
  "Company Profile - TH": "โปรไฟล์บริษัท - TH",
  "Leadership Team": "ทีมผู้บริหารระดับสูง",
  "<svg fill=\"none\" height=\"20\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" viewbox=\"0 0 24 24\" width=\"20\"><path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"></path><polyline points=\"7 10 12 15 17 10\"></polyline><line x1=\"12\" x2=\"12\" y1=\"15\" y2=\"3\"></line></svg>\n            Download Company Profile\n            <svg fill=\"none\" height=\"16\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" style=\"margin-left: 0.2rem;\" viewbox=\"0 0 24 24\" width=\"16\"><polyline points=\"6 9 12 15 18 9\"></polyline></svg>": "<svg fill=\"none\" height=\"20\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" viewbox=\"0 0 24 24\" width=\"20\"><path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"></path><polyline points=\"7 10 12 15 17 10\"></polyline><line x1=\"12\" x2=\"12\" y1=\"15\" y2=\"3\"></line></svg>\n            ดาวน์โหลดโปรไฟล์บริษัท\n            <svg fill=\"none\" height=\"16\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" style=\"margin-left: 0.2rem;\" viewbox=\"0 0 24 24\" width=\"16\"><polyline points=\"6 9 12 15 18 9\"></polyline></svg>",
  "We Come From Hotels:": "เรามาจากวงการโรงแรม:",
  "We Act as Your Team:": "เราทำหน้าที่เป็นทีมของคุณ:",
  "We Focus on Net Revenue:": "เราเน้นที่รายได้สุทธิ:",
  "We Are Transparent:": "เราโปร่งใส:",
  "We Are Here:": "เราอยู่ที่นี่:",
  "We Are Flexible:": "เรามีความยืดหยุ่น:",
  "Vision:": "วิสัยทัศน์:",
  "Mission:": "พันธกิจ:",
  "Revenue Leakage Funnel": "กรวยการรั่วไหลของรายได้",
  "Potential revenue lost through pricing operational gaps": "รายได้ที่อาจสูญเสียผ่านช่องว่างในการดำเนินการด้านราคา",
  "Leak -3%": "รั่วไหล -3%",
  "Leak -5%": "รั่วไหล -5%",
  "Leak -4%": "รั่วไหล -4%",
  "Independent Hotels:": "โรงแรมอิสระ:",
  "Boutique &amp; Lifestyle Hotels:": "โรงแรมบูติกและไลฟ์สไตล์:",
  "Serviced Apartments &amp; Resorts:": "เซอร์วิสอพาร์ทเมนท์และรีสอร์ท:",
  "Small Hotel Groups (20–250 rooms):": "กลุ่มโรงแรมขนาดเล็ก (20–250 ห้อง):",
  "Hotels with Heavy OTA Dependency:": "โรงแรมที่พึ่งพา OTA อย่างหนัก:",
  "<a data-i18n=\"blog-about-title\" href=\"blog/about-crs-central.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">About CRS Central – Smarter Revenue. Stronger Performance.</a>": "<a data-i18n=\"blog-about-title\" href=\"blog/about-crs-central.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">เกี่ยวกับ CRS Central – รายได้ที่ฉลาดขึ้น ประสิทธิภาพที่แข็งแกร่งขึ้น</a>",
  "<a href=\"blog/hotel-digital-marketing-social-media.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">Hotel Digital Marketing From $299/Month — Instagram, Facebook &amp; YouTube</a>": "<a href=\"blog/hotel-digital-marketing-social-media.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">การตลาดดิจิทัลโรงแรม เริ่มต้นที่ $299/เดือน — Instagram, Facebook &amp; YouTube</a>",
  "<a href=\"blog/hotel-website-development-direct-bookings.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">Hotel Website Design From $380 — Built for Direct Bookings</a>": "<a href=\"blog/hotel-website-development-direct-bookings.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">ออกแบบเว็บไซต์โรงแรม เริ่มต้นที่ $380 — สร้างมาเพื่อการจองตรง</a>",
  "<a href=\"blog/affordable-pms-channel-manager-for-independent-hotels.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">Affordable Hotel PMS, Channel Manager &amp; Booking Engine — From $110/Month</a>": "<a href=\"blog/affordable-pms-channel-manager-for-independent-hotels.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">PMS โรงแรม, Channel Manager และระบบการจองราคาประหยัด — เริ่มต้นที่ $110/เดือน</a>",
  "<a data-i18n=\"blog-26-title\" href=\"blog/hotel-full-losing-money-revenue-management.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">Your Hotel Is Full Tonight — And You're Still Losing Money. Here's Why.</a>": "<a data-i18n=\"blog-26-title\" href=\"blog/hotel-full-losing-money-revenue-management.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">โรงแรมของคุณเต็มคืนนี้ — และคุณยังขาดทุนอยู่ นี่คือเหตุผล</a>",
  "<a data-i18n=\"blog-7-title\" href=\"blog/danang-hotels-rate-fencing-increase-revenue.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">How Da Nang Hotels Can Increase Revenue by 18–30% With Proper Rate Fencing</a>": "<a data-i18n=\"blog-7-title\" href=\"blog/danang-hotels-rate-fencing-increase-revenue.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">โรงแรมในดานังสามารถเพิ่มรายได้ 18–30% ได้อย่างไรด้วยการจัดกรอบราคาที่เหมาะสม</a>",
  "<a data-i18n=\"blog-5-title\" href=\"blog/danang-hotels-struggle-during-low-season.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">The Real Reason Da Nang Hotels Struggle During Low Season</a>": "<a data-i18n=\"blog-5-title\" href=\"blog/danang-hotels-struggle-during-low-season.html\" style=\"text-decoration: none; color: inherit; transition: var(--transition);\">เหตุผลที่แท้จริงที่โรงแรมในดานังประสบปัญหาในช่วงโลว์ซีซั่น</a>"
}

add_translations(d)
