# -*- coding: utf-8 -*-
from accumulate_th import add_translations

d = {
  "Request an In-Person Meeting": "ขอนัดหมายพบปะด้วยตนเอง",
  "GSTIN: 36AANCC2942H1ZJ": "GSTIN: 36AANCC2942H1ZJ",
  "Hotel software that helps you earn more.": "ซอฟต์แวร์โรงแรมที่ช่วยให้คุณมีรายได้เพิ่มขึ้น",
  "One connected system for your hotel": "ระบบเดียวที่เชื่อมต่อถึงกันสำหรับโรงแรมของคุณ",
  "A simple PMS your team can learn in a day.": "PMS ที่ใช้งานง่ายซึ่งทีมของคุณเรียนรู้ได้ในวันเดียว",
  "Update once. Sell everywhere.": "อัปเดตครั้งเดียว ขายได้ทุกที่",
  "Get more direct bookings. Pay only 8%.": "รับการจองตรงมากขึ้น จ่ายเพียง 8%",
  "Simple, transparent pricing": "ราคาเรียบง่าย โปร่งใส",
  "Software gives you the tools. Revenue management shows you how to use them.": "ซอฟต์แวร์มอบเครื่องมือให้คุณ การจัดการรายได้แสดงวิธีใช้งานเครื่องมือเหล่านั้นให้คุณ",
  "See StayCRS in action": "ดูการทำงานของ StayCRS",
  "PMS": "PMS",
  "Channel Manager": "Channel Manager",
  "Booking Engine": "ระบบจองห้องพัก",
  "Cloud-based": "ทำงานบนคลาวด์",
  "Connected": "เชื่อมต่อถึงกัน",
  "Built-in guest loyalty": "ระบบสมาชิกแขกในตัว",
  "Reservations": "การจอง",
  "Front desk": "แผนกต้อนรับ",
  "Billing": "การเรียกเก็บเงิน",
  "Housekeeping": "แม่บ้าน",
  "Reports": "รายงาน",
  "Real-time sync": "ซิงค์แบบเรียลไทม์",
  "Rate parity": "ความเท่าเทียมของราคา",
  "Yield rules": "กฎการปรับราคา",
  "Exports": "การส่งออกข้อมูล",
  "Flexible": "ยืดหยุ่น",
  "Mobile friendly": "รองรับมือถือ",
  "Competitor rates": "ราคาของคู่แข่ง",
  "Support": "การสนับสนุน",
  "Easy for guests": "ง่ายสำหรับแขก",
  "Always in sync": "ข้อมูลตรงกันเสมอ",
  "Everywhere you are": "ทุกที่ที่คุณอยู่",
  "Mobile first": "ออกแบบเพื่อมือถือเป็นหลัก",
  "Expert backed": "สนับสนุนโดยผู้เชี่ยวชาญ",
  "PMS + Channel Manager": "PMS + Channel Manager",
  "Contact": "ติดต่อ",
  "PMS, Channel Manager and Booking Engine in one connected system, backed by hotel revenue experts.": "PMS, Channel Manager และระบบจองห้องพักในระบบเดียวที่เชื่อมต่อถึงกัน สนับสนุนโดยผู้เชี่ยวชาญด้านรายได้โรงแรม",
  "Run the property, sell on every channel and win more direct bookings, all from one place.": "บริหารที่พัก ขายบนทุกช่องทาง และชนะการจองตรงได้มากขึ้น ทั้งหมดจากที่เดียว",
  "Run your whole property from one simple cloud system.": "บริหารที่พักทั้งหมดของคุณจากระบบคลาวด์ที่ใช้งานง่ายเพียงระบบเดียว",
  "Update rates and availability once. Every OTA stays in sync.": "อัปเดตราคาและความพร้อมให้บริการครั้งเดียว ทุก OTA จะได้รับการซิงค์",
  "Get direct bookings from your website for a flat 8%.": "รับการจองตรงจากเว็บไซต์ของคุณด้วยค่าธรรมเนียมคงที่ 8%",
  "A modern cloud system for check-in, reservations, billing and housekeeping. Works on desktop, tablet and mobile.": "ระบบคลาวด์ที่ทันสมัยสำหรับการเช็คอิน การจอง การเรียกเก็บเงิน และแม่บ้าน ใช้งานได้บนเดสก์ท็อป แท็บเล็ต และมือถือ",
  "No servers and no on-site IT. No annual maintenance fee and no limit on users.": "ไม่ต้องมีเซิร์ฟเวอร์และไม่มีไอทีประจำสถานที่ ไม่มีค่าบำรุงรักษารายปีและไม่จำกัดผู้ใช้งาน",
  "Bookings from OTAs and your website arrive automatically.": "การจองจาก OTA และเว็บไซต์ของคุณจะเข้ามาโดยอัตโนมัติ",
  "Build your own loyalty programme inside the PMS.": "สร้างโปรแกรมสมาชิกของคุณเองภายใน PMS",
  "Handle group and individual bookings and track them by market segment.": "จัดการการจองแบบกลุ่มและแบบบุคคล พร้อมติดตามตามกลุ่มตลาด",
  "Fast check-in and check-out, with guest profiles saved for next time.": "เช็คอินและเช็คเอาท์อย่างรวดเร็ว พร้อมบันทึกโปรไฟล์แขกสำหรับครั้งต่อไป",
  "Issue invoices, receipts and tax receipts from the system.": "ออกใบแจ้งหนี้ ใบเสร็จรับเงิน และใบกำกับภาษีจากระบบ",
  "Daily task lists for the housekeeping team.": "รายการงานประจำวันสำหรับทีมแม่บ้าน",
  "Ready-made reports for occupancy, revenue and more.": "รายงานสำเร็จรูปสำหรับอัตราการเข้าพัก รายได้ และอื่นๆ",
  "Send rates and availability to every major OTA from one screen, and bring every reservation back automatically.": "ส่งราคาและความพร้อมให้บริการไปยัง OTA รายใหญ่ทุกรายจากหน้าจอเดียว และนำการจองทั้งหมดกลับมาโดยอัตโนมัติ",
  "Room status updates on OTAs and your website as bookings happen.": "สถานะห้องพักอัปเดตบน OTA และเว็บไซต์ของคุณทันทีที่มีการจอง",
  "Keep your rates consistent across channels with simple rate controls.": "รักษาราคาให้สม่ำเสมอในทุกช่องทางด้วยการควบคุมราคาที่เรียบง่าย",
  "Set your own rules to raise or lower rates automatically.": "ตั้งกฎของคุณเองเพื่อปรับเพิ่มหรือลดราคาโดยอัตโนมัติ",
  "Download your rates and data as Excel or PDF.": "ดาวน์โหลดราคาและข้อมูลของคุณเป็น Excel หรือ PDF",
  "Use it with the StayCRS PMS or with your existing PMS.": "ใช้กับ StayCRS PMS หรือกับ PMS ปัจจุบันของคุณ",
  "Manage your channels from your phone.": "จัดการช่องทางของคุณจากมือถือ",
  "Optional rate shopping service, powered by CRS Central.": "บริการเช็คราคาตัวเลือกเสริม สนับสนุนโดย CRS Central",
  "Real people ready to help when you need them.": "มีทีมงานที่เป็นคนจริงๆ พร้อมช่วยเหลือเมื่อคุณต้องการ",
  "Turn your website and social pages into a booking channel that costs far less than an OTA.": "เปลี่ยนเว็บไซต์และหน้าโซเชียลของคุณให้เป็นช่องทางการจองที่ถูกกว่า OTA มาก",
  "Every booking that comes through an OTA costs you around 18%. Through the StayCRS Booking Engine you pay a straight 8% on your direct bookings. Same guest, more profit in your pocket.": "ทุกการจองที่ผ่าน OTA มีค่าใช้จ่ายประมาณ 18% แต่ด้วยระบบจอง StayCRS คุณจ่ายเพียง 8% สำหรับการจองตรง แขกคนเดียวกัน แต่กำไรเข้ากระเป๋าคุณมากกว่า",
  "Illustrative example. Actual OTA commission varies by channel and agreement.": "ตัวอย่างเพื่อประกอบการอธิบาย ค่าคอมมิชชั่น OTA จริงจะแตกต่างกันไปตามช่องทางและข้อตกลง",
  "A simple booking flow guests can finish in a few taps.": "ขั้นตอนการจองที่ง่าย แขกสามารถทำเสร็จได้ในไม่กี่คลิก",
  "Rates and availability come live from the PMS, so no mismatches.": "ราคาและความพร้อมให้บริการมาจาก PMS โดยตรง ดังนั้นจึงไม่มีข้อมูลที่ไม่ตรงกัน",
  "Works on your hotel website and your key social media pages.": "ใช้งานได้บนเว็บไซต์โรงแรมและหน้าโซเชียลมีเดียหลักของคุณ",
  "Fully responsive, since most travellers book on their phones.": "ตอบสนองได้เต็มรูปแบบ เนื่องจากนักเดินทางส่วนใหญ่จองผ่านมือถือ",
  "Built with pricing expertise from CRS Central.": "สร้างขึ้นด้วยความเชี่ยวชาญด้านราคาจาก CRS Central",
  "No setup surprises. Pick what you need.": "ไม่มีค่าติดตั้งแอบแฝง เลือกเฉพาะสิ่งที่คุณต้องการ",
  "Cloud PMS and Channel Manager together, with real people for support.": "Cloud PMS และ Channel Manager พร้อมกัน โดยมีทีมงานตัวจริงคอยสนับสนุน",
  "On direct bookings made through the Booking Engine. Pay only when you earn.": "สำหรับการจองตรงผ่านระบบจองห้องพัก จ่ายเฉพาะเมื่อคุณมีรายได้",
  "Hotel revenue management means selling the right room, at the right price, on the right channel, at the right time. With StayCRS it works hand in hand with your system. The CRS Central revenue team, led by specialists with more than 17 years in luxury hospitality, uses your PMS data to set rates, pushes them to every OTA through the Channel Manager, and steers more guests to your Booking Engine, where you pay 8% instead of around 18%.": "การจัดการรายได้โรงแรมหมายถึงการขายห้องที่ใช่ ในราคาที่เหมาะสม ผ่านช่องทางที่ถูกต้อง และในเวลาที่เหมาะสม เมื่อใช้ StayCRS ระบบจะทำงานสอดคล้องกับระบบของคุณ ทีมรายได้ของ CRS Central ซึ่งนำโดยผู้เชี่ยวชาญที่มีประสบการณ์ด้านโรงแรมหรูกว่า 17 ปี ใช้ข้อมูล PMS ของคุณในการตั้งราคา ส่งไปยังทุก OTA ผ่าน Channel Manager และดึงดูดแขกให้เข้าสู่ระบบจองห้องพักของคุณ ซึ่งคุณจะเสียค่าธรรมเนียมเพียง 8% แทนที่จะเป็น 18%",
  "Request a demo and we will respond within 24 hours.": "ขอดูการสาธิตระบบ และเราจะตอบกลับภายใน 24 ชั่วโมง",
  "Hotel PMS, Channel Manager and Booking Engine, backed by CRS Central revenue experts.": "PMS โรงแรม, Channel Manager และระบบการจอง สนับสนุนโดยผู้เชี่ยวชาญด้านรายได้ของ CRS Central",
  "© <span id=\"yr\"></span> StayCRS. A brand owned and operated by CRS Chauhan Private Limited.": "© <span id=\"yr\"></span> StayCRS แบรนด์ที่เป็นเจ้าของและดำเนินการโดย CRS Chauhan Private Limited.",
  "Get a Demo": "ขอการสาธิต",
  "See Pricing": "ดูราคา",
  "Learn more →": "เรียนรู้เพิ่มเติม →",
  "Request a demo or free trial": "ขอการสาธิตหรือทดลองใช้ฟรี",
  "Request a demo": "ขอสาธิตระบบ",
  "Get a Quote": "ขอใบเสนอราคา",
  "Explore Revenue Management at crscentral.com": "สำรวจการจัดการรายได้ที่ crscentral.com",
  "WhatsApp Us": "WhatsApp หาเรา",
  "crscentral.com": "crscentral.com",
  "Terms &amp; Conditions": "ข้อตกลงและเงื่อนไข",
  "Privacy and Data Protection Policy": "นโยบายความเป็นส่วนตัวและการคุ้มครองข้อมูล",
  "per month, PMS + Channel Manager": "ต่อเดือน, PMS + Channel Manager",
  "on direct bookings via the Booking Engine": "สำหรับการจองตรงผ่านระบบจอง",
  "/ month": "/ เดือน",
  "Occupancy, pace and guest mix guide smarter pricing.": "อัตราการเข้าพัก จังหวะการจอง และส่วนผสมของแขกเป็นแนวทางในการตั้งราคาที่ชาญฉลาดขึ้น",
  "One rate change reaches every OTA at once.": "การเปลี่ยนราคาหนึ่งครั้งเข้าถึงทุก OTA พร้อมกัน",
  "A better channel mix, with more bookings at 8%.": "ส่วนผสมช่องทางจำหน่ายที่ดีกว่า พร้อมการจองเพิ่มขึ้นที่ 8%",
  "Thank you. Our team will contact you within 24 hours.": "ขอบคุณ ทีมงานของเราจะติดต่อกลับภายใน 24 ชั่วโมง",
  "Mon-Sun, 8:00 a.m.-7:00 p.m.": "จันทร์-อาทิตย์, 8:00 น. - 19:00 น.",
  "Request a Demo": "ขอดูสาธิต",
  "USD 110": "110 USD",
  "8% flat": "คงที่ 8%",
  "Commission you pay": "ค่าคอมมิชชั่นที่คุณจ่าย",
  "On a USD 1,000 booking": "สำหรับการจอง 1,000 USD",
  "You keep more": "คุณเก็บกำไรได้มากขึ้น",
  "PMS data": "ข้อมูล PMS",
  "<b>Commission you pay</b>": "<b>ค่าคอมมิชชั่นที่คุณจ่าย</b>",
  "Around 18%": "ประมาณ 18%",
  "<b>On a USD 1,000 booking</b>": "<b>สำหรับการจอง 1,000 USD</b>",
  "About USD 180": "ประมาณ 180 USD",
  "USD 80": "80 USD",
  "<b>You keep more</b>": "<b>คุณเก็บกำไรได้มากขึ้น</b>",
  "About USD 100 per USD 1,000": "ประมาณ 100 USD ต่อ 1,000 USD",
  "Booking via OTA": "การจองผ่าน OTA",
  "Booking via StayCRS": "การจองผ่าน StayCRS"
}

add_translations(d)
